name: Run Builds
 
on: 
  push:
  schedule: 
    - cron: "* * */1 * *"

permissions:
  contents: write

jobs:
  build:
    name: Run Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
 
      - name: Run composer install
        run: composer install -n --prefer-dist
 
      - name: Run phar build
        run: php dockerfile-laravel app:build dockerfile-laravel --build-version=1.0.4

      - name: Run all oses builds
        run: vendor/bin/haulable builds/dockerfile-laravel --platform="All Platforms"

      - uses: actions/upload-artifact@v4
        with:
          name: windows_x64-artifact
          path: windows_x64/

      - uses: actions/upload-artifact@v4
        with:
          name: linux_aarch64-artifact
          path: linux_aarch64/

      - uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64-artifact
          path: linux_x86_64/

      - uses: actions/upload-artifact@v4
        with:
          name: macos_apple-artifact
          path: macos_apple/

      - uses: actions/upload-artifact@v4
        with:
          name: macos_intel-artifact
          path: macos_intel/


     