name: Run Builds
 
on: [push]

permissions:
  contents: write

jobs:
  build:
    name: Run Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
 
      - name: Run composer install
        run: composer install -n --prefer-dist
 
      - name: Run phar build
        run: php dockerfile-laravel app:build dockerfile-laravel --build-version=1.0.4

      - name: Run windows builds
        run: vendor/bin/haulable builds/dockerfile-laravel --platform="All Platforms"
    
      - name: Move builds into the builds folder
        run: mv windows_x64 builds/windows_x64 && mv linux_aarch64 builds/linux_aarch64 && mv linux_x86_64 builds/linux_x86_64 && mv macos_apple builds/macos_apple && mv macos_intel builds/macos_intel 

      - name: CHECK files
        run: ls -l builds/

      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: builds/windows_x64/